import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import axios from "axios";
import Link from "next/link";

export default function Home() {
  const url = "https://fakestoreapi.com/products/categories";
  const [data, setData] = useState([]);

  const fetchInfo = () => {
    return axios.get(url).then((res) => setData(res.data));
  };

  useEffect(() => {
    fetchInfo();
  }, []);
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={styles.flex}>
        <div className={styles.banner}>
          <Image
            src="/illustration.svg"
            alt=""
            height={350}
            width={350}
            className={styles.image}
          ></Image>

          <div className={styles.flex}></div>
          <center>
            <h1 className={styles.heading}>Your One Stop to Branded Goods!</h1>
          </center>
          <p className={styles.para}>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique
            ipsam perferendis neque! Excepturi est hic error nam deserunt
            provident natus dicta ab? Distinctio beatae inventore magni, itaque
            adipisci perferendis fugit. Inventore, in dolorem! Tenetur
            molestias, quidem temporibus maxime explicabo eum sunt excepturi
            quam rem exercitationem assumenda repellendus in, quae maiores
            aliquam neque.
          </p>
          <center>
            <Link href="/products">
              <button className={styles.button}>Explore More</button>
            </Link>
          </center>
        </div>
      </div>
      <h1 className={styles.categories}>Categories</h1>
      <div className={styles.flexbox}>
        {data.map((categories) => (
          <div key={categories.toString()} className={styles.card}>
            {categories}
          </div>
        ))}
      </div>
    </>
  );
}
